server:
  port: 9527

eureka:
  client: #\u5BA2\u6237\u7AEF\u6CE8\u518C\u8FDBeureka\u670D\u52A1\u5217\u8868\u5185
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true
zuul:
  routes:
    mytest.serviceId: microservicecloud-dept
    mytest.path: /test/**
  ignored-services: microservicecloud-dept
  prefix: /sunlands
